import {
  charity,
  dashboard,
  dobu,
  ecommerce,
  quizzical,
  audio,
  nextjsEcommerce,
  clock,
  gpt3,
  inabox,
  memeGame,
  noteApp,
  tenzieGame,
  tictactoe,
  typingGame,
  audioUIUX,
  charityUIUX,
  communityUIUX,
  droneUIUX,
  movieUIUX,
  portfolioUIUX,
  opennet,
  bethingliving,
  bheaBlog,
  bheaIntegration,
  blissgrow,
  parichaya,
  rect82,
  samosachai,
  sriraksha,
  yenrich
} from "../Image";

// Projects Data for Projects Card
export const projectsData = [
  {
    title: "OpenNets — Event Management Platform",
    description:
      "📅Led full design and development, including logo creation and website setup. Built an engaging event-focused experience optimized for clarity and speed.",
    websiteURL: "https://www.opennets.com/",
    image: opennet,
    type: "bhea",
    languages: ["WordPress", "UI Design", "Event Management"],
  },
  {
    title: "Bhea - Corporate Management Website",
    description: 
      "Handled maintenance tasks such as lead tracking, new page development, email system fixes and payment gateway integration. Improved overall reliability and visual consistency.",
    websiteURL: "https://www.bhea.com/",
    image: bheaIntegration,
    type: "bhea",
    languages: ["WordPress", "Maintenance", "Troubleshooting", "Integration"],
  },
  {
    title: "Samosachai - Event Management Website",
    description:
      "📅Designed and developed a complete event management website integrating smooth navigation and modern design principles to enhance brand presence.",
    websiteURL: "https://www.samosach.ai/",
    image: samosachai,
    type: "bhea",
    languages: ["WordPress", "UI Design", "Event Management"],
  },
    {
    title: "Bhea - Corporate Blog Management",
    description:
      "Enhanced blog usability and visual hierarchy for better readability and engagement. Managed content flow and styling.",
    websiteURL: "https://www.bhea.com/blog/",
    image: bheaBlog,
    type: "bhea",
    languages: ["WordPress", "Content Management", "UI/UX Enhancement"],
  },
  {
    title: "Rect82 - Education Platform for Girl Child",
    description:
      "📅Designed and developed a meaningful education‌al charity website aimed at empowering girls. Integrated donation form and overall process.",
    image: rect82,
    type: "bhea",
    languages: ["WordPress", "UI Design", "Integration"],
  },
  {
    title: "BlissGrow - E-Commerce Product Website",
    description:
    "Enhanced user experience by improving checkout flow and updating product listings. Focused on creating a smoother, modern shopping experience.",
    websiteURL: "https://www.blissgrow.in/",
    image: blissgrow,
    type: "bhea",
    languages: ["WordPress", "UI/UX Optimization", "WooCommerce"],
  },
  {
    title: "Yenrich - E-Commerce Platform",
    description:
      "Developed a full-featured e-commerce site from scratch, focusing on user-friendly product navigation and seamless checkout experience.",
    websiteURL: "https://www.yenrich.in/",
    image: yenrich,
    type: "bhea",
    languages: ["WordPress", "UI Design", "WooCommerce"],
  },
  {
    title: "Sriraksha - Construction Company Website",
    description:
      "Updated design components to modernize look and feel while maintaining brand consistency. Integrated event management system.",
    websiteURL: "https://www.sriraksha.co.in/",
    image: sriraksha,
    type: "bhea",
    languages: ["WordPress", "Maintenance", "Event Management"],
  },
  {
    title: "Parichaya - Dating Platform",
    description:
      "Implemented secure Login/Register and user management features for a dating web application.",
    websiteURL: "https://parichaya.co/",
    image: parichaya,
    type: "bhea",
    languages: ["WordPress", "User Authentication", "User Management"],
  },
  {
    title: "BethLiving - Interior Blog Page Development",
    description:
      "Designed and implemented a complete blog system to support marketing content for Beth Living’s main website.",
    websiteURL: "https://bethliving.com/blog/",
    image: bethingliving,
    type: "bhea",
    languages: ["WordPress", "UI Design", "Event Management"],
  },
  {
    title: "NextJs Ecommerce",
    description:
      "🛒Ecommerce with accurate functionality such as add to cart, checkout",
    codeUrl: "https://github.com/Rayy-007/nextjs-ecommerce-project",
    websiteURL: "https://nextjs-ecommerce-project-khants-projects.vercel.app/",
    image: nextjsEcommerce,
    type: "website",
    languages: ["NextJs", "TypeScript", "Tailwind", "DaisyUI", "MongoDb"],
  },
  {
    title: "Audieo Ecommerce",
    description:
      "🔉The commerce website that allows customers to effortlessly explore business products, make payments interact with business dynamically.",
    codeUrl: "https://github.com/tin0312/audiophile-ecommerce",
    websiteURL: "https://audio-website-by-khant.netlify.app/",
    image: audio,
    type: "website",
    languages: ["NextJs", "TypeScript", "Tailwind", "Firebase"],
  },
  {
    title: "DoBu Martial Arts",
    description:
      "🏋️‍♀️DoBu Martial Arts Project is a visually appealing website crafted entirely with my own design.",
    codeUrl: "https://github.com/Rayy-007/DoBu-Martial-arts-project",
    websiteURL: "https://dobumartialarts.netlify.app/",
    image: dobu,
    type: "website",
    languages: ["JavaScript", "JQuery", "HTML", "CSS"],
  },
  {
    title: "Dashboard Website",
    description:
      "🎨Dashboard Simple Project is a sleek and modern web application designed as an admin dashboard.",
    codeUrl: "https://github.com/Rayy-007/dashboard-simple-project",
    websiteURL: "https://dashboard-simple-project.netlify.app/",
    image: dashboard,
    type: "website",
    languages: ["HTML", "CSS"],
  },
  {
    title: "Charity Organization Website",
    description:
      "⚡ Full-stack development project for MerryMeal - Charity Organization.",
    codeUrl: "https://github.com/Rayy-007/meals-on-wheel-project",
    websiteURL: "https://charity-organization-by-khant.netlify.app/",
    image: charity,
    type: "website",
    languages: ["React", "Java", "SpringBoot"],
  },
  {
    title: "Ecommerce Project",
    description:
      "🛒This Ecommerce Project is a comprehensive web application focused on building a responsive ecommerce website.",
    codeUrl: "https://github.com/Rayy-007/Ecommerce-Website-By-Khant",
    websiteURL: "https://multi-page-ecommerce-by-khant.netlify.app/",
    image: ecommerce,
    type: "website",
    languages: ["HTML", "CSS", "JavaScript"],
  },
  {
    title: "Clone GPT3 Website",
    description:
      "🤖A clone of the OpenAI GPT-3 website showcasing its capabilities and features.",
    codeUrl: "https://github.com/Rayy-007/GPT-3-React-Web",
    websiteURL: "https://gpt3-react-khant.netlify.app/",
    image: gpt3,
    type: "website",
    languages: ["React", "Responsive"],
  },
  {
    title: "React Typing Speed Game",
    description:
      "⌨️ Test your typing speed with this fun and interactive React typing game.",
    codeUrl: "https://github.com/Rayy-007/react-typing-game",
    websiteURL: "https://react-typing-game-khant.netlify.app/",
    image: typingGame,
    type: "app",
    languages: ["React", "JavaScript", "HTML", "CSS"],
  },
  {
    title: "TicTacToe Game",
    description:
      "🎮 Enjoy the classic TicTacToe game with friends or against the computer.",
    codeUrl: "https://github.com/Rayy-007",
    websiteURL: "https://react-tictactoe-game-project.netlify.app",
    image: tictactoe,
    type: "app",
    languages: ["React", "JavaScript", "HTML", "CSS"],
  },
  {
    title: "MDE Note App with React",
    description:
      "📝 Create and manage your notes with Markdown support using this React-based MDE (Markdown Editor) note-taking app.",
    codeUrl: "https://github.com/Rayy-007/react-mde-note-app",
    websiteURL: "https://react-note-khant.netlify.app/",
    image: noteApp,
    type: "app",
    languages: ["React", "Markdown", "JavaScript", "CSS"],
  },
  {
    title: "Tenzies Game",
    description: "🎲 Test your luck and speed with this fast-paced dice game.",
    codeUrl: "https://github.com/Rayy-007",
    websiteURL: "https://react-project-tenzies-game.netlify.app",
    image: tenzieGame,
    type: "app",
    languages: ["React", "JavaScript", "HTML", "CSS"],
  },
  {
    title: "Meme Generator",
    description:
      "🎭 Create hilarious memes easily using this React.js application.",
    codeUrl: "https://github.com/Rayy-007/react-project-meme",
    websiteURL: "https://react-projecty-meme.netlify.app/",
    image: memeGame,
    type: "app",
    languages: ["React", "JavaScript", "HTML", "CSS"],
  },
  {
    title: "Clock Chrome Extension",
    description:
      "⏰ Stay organized and track time with this simple clock Chrome extension.",
    codeUrl: "https://github.com/Rayy-007/Creative-Clock-Web",
    websiteURL: "https://clock-by-khant.netlify.app/",
    image: clock,
    type: "website",
    languages: ["JavaScript", "HTML", "CSS"],
  },
  {
    title: "In A Box Food Website",
    description:
      "🍱 Explore delicious meals and order food conveniently with this multiple-page website.",
    codeUrl: "https://github.com/Rayy-007",
    websiteURL: "https://inabox-my-first-website.netlify.app/",
    image: inabox,
    type: "website",
    languages: ["HTML", "CSS", "JavaScript", "Bootstrap"],
  },
  {
    title: "Audio Ecommerce",
    description: "🎧 UI/UX design for an audio ecommerce platform.",
    image: audioUIUX,
    type: "uiux",
    languages: ["Figma", "UI UX"],
  },
  {
    title: "Charity",
    description: "🤝 uiux design for a charity organization website.",
    image: charityUIUX,
    type: "uiux",
    languages: ["Figma", "UI UX"],
  },
  {
    title: "Community",
    description: "🏘️ uiux design for a community platform.",
    image: communityUIUX,
    type: "uiux",
    languages: ["Figma", "UI UX"],
  },
  {
    title: "Drone",
    description: "🚁 uiux design for a drone service website.",
    image: droneUIUX,
    type: "uiux",
    languages: ["Figma", "UI UX"],
  },
  {
    title: "Movie Search",
    description: "🎬 uiux design for a movie search application.",
    image: movieUIUX,
    type: "uiux",
    languages: ["Figma", "UI UX"],
  },
  {
    title: "Portfolio",
    description: "📁 uiux design for a portfolio website.",
    image: portfolioUIUX,
    type: "uiux",
    languages: ["Figma", "UI UX"],
  },
];
